name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.8.3
  provider: ^6.1.5+1
  google_fonts: ^6.3.1
  intl: ^0.20.2

  fl_chart: 0.68.0
  vector_math: ^2.1.4
  flutter_chat_ui: 2.9.1 # Pinned to exact version
  flutter_chat_types: ^3.6.2
  bubble: ^1.2.1
  crypto: ^3.0.3
  sqflite_common_ffi_web: ^1.0.1+1
  shared_preferences: ^2.0.15 # Added shared_preferences
  characters: 1.4.0 # Pinned to exact version resolved by Pub
  material_color_utilities: 0.11.1 # Pinned to exact version resolved by Pub
  meta: ^1.17.0 # Pinned to exact version resolved by Pub
  local_auth: ^3.0.0
  csv: ^6.0.0
  flutter_local_notifications: ^19.4.2
  pdf: ^3.11.3
  printing: ^5.14.2
  excel: ^4.0.6
  file_saver: ^0.3.1
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.0
  timezone: ^0.10.1
  dropdown_search: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.6.1
  build_runner: ^2.10.4
  sqflite_common_ffi: ^2.3.6
  test_api: ^0.7.7 # Pinned to exact version resolved by Pub

flutter:
  uses-material-design: true
